import {useState,type FormEvent}from'react';
import {AnimatePresence,motion,useReducedMotion}from'motion/react';
import {ArrowRight,BookOpen,Check,Clock3,Eye,Menu,RefreshCcw,SkipForward,Volume2,VolumeX,X}from'lucide-react';
import ClassroomScene from'./environment/ClassroomScene';
import SupportTransformation from'./animations/SupportTransformation';
import LeoCharacter,{type LeoPose}from'./characters/LeoCharacter';
import {useDemo,type DemoAnswers}from'./DemoContext';

type Answers=DemoAnswers;
const timeline=['Arrival','Reading','Assignment','Memory','Steps','Transition','Energy','Support'];
const choices={focus:[['I keep working',0],['I notice it, then return',1],['I usually lose track of the task',3]],task:[['I can work through it',0],['I need a few reminders',2],['I often stop before finishing',3]],transition:[['Easy to switch',0],['I need a little time',2],["It's very hard to stop",3]],energy:[['Calm',0],['Restless',2],['Tired',2],['Very energetic',1]]}as const;
const sceneNames=['Morning Classroom','Focus in class','Long assignment','Memory moment','Follow the steps','Class transition','Body & energy','Support preference','Support Profile','Support transformation',"Today's Plan"];

export default function JuryDemo(){
 const reduced=useReducedMotion();const{demoMode,demoUser,currentScene:scene,setCurrentScene:setScene,answers,setAnswers,supportProfile:profile,enterDemo,resetDemo}=useDemo();const[selected,setSelected]=useState<string[]>([]);const[sequence,setSequence]=useState<string[]>([]);const[repeats,setRepeats]=useState(0);const[sound,setSound]=useState(false);const[menu,setMenu]=useState(false);const[reaction,setReaction]=useState(false);
 const go=(n=scene+1)=>{setReaction(false);setSelected([]);setSequence([]);setScene(Math.min(n,10))};
 const answer=(key:keyof Answers,value:number|string)=>{setAnswers(x=>({...x,[key]:value}));setReaction(true);window.setTimeout(()=>go(),reduced?80:650)};
 const need=(n:number)=>n>=3?'Needs More Support':n>=1.5?'May Need Support':'Doing Well';
 const pose:LeoPose=scene===1?(reaction?(answers.focus===3?'thinking':'smile'):'reading'):scene===2?'thinking':scene===4?'teacher':scene===5?'packing':scene===6?(['reading','restless','tired','energetic'][answers.energy??0]as LeoPose):reaction?'smile':'reading';
 const board=scene===1?'READ · Pages 10–12':scene===2?'Independent work':scene===3?'Please remember these':scene===4?'1. Blue book  2. Beside pencil  3. Tap star':scene===5?'Math starts next':scene===6?'Quiet learning time':scene===7?'We can try a support':'Good morning, everyone!';
 const restart=()=>{resetDemo();setMenu(false);setRepeats(0)};
 if(!demoMode)return <DemoEntry onEnter={enterDemo}/>;
 const learner=demoUser?.name||'Leo';
 return <main className="jury-demo">
  <header className="demo-header"><a className="demo-brand" href="/" aria-label="Exit HEBAT Jury Demo"><span>H</span><b>HEBAT</b><small>Jury Demo</small></a><div className="demo-head-actions"><button onClick={()=>setSound(x=>!x)} aria-label={`Sound ${sound?'on':'off'}`}>{sound?<Volume2/>:<VolumeX/>}<span>Sound {sound?'On':'Off'}</span></button><button onClick={()=>setMenu(x=>!x)} aria-expanded={menu} aria-label="Presenter controls"><Menu/></button></div>{menu&&<div className="presenter-menu"><b>Presenter controls</b><button onClick={restart}><RefreshCcw/>Restart Demo</button><button onClick={()=>go()}><SkipForward/>Skip Scene</button><button onClick={()=>go(8)}><Eye/>Skip to Support Profile</button><a href="/"><X/>Exit Demo</a></div>}</header>
  <div className="school-timeline" aria-label={`School-day progress: ${sceneNames[scene]}`}><div className="timeline-label"><span>{learner}'s school day</span><b>{sceneNames[scene]}</b></div><div className="timeline-track">{timeline.map((x,i)=><div key={x} className={i<=scene?'done':''}><i>{i<scene?<Check/>:null}</i><span>{x}</span></div>)}</div></div>
  <AnimatePresence mode="wait"><motion.div key={scene} className="demo-stage" initial={{opacity:0,x:reduced?0:18}} animate={{opacity:1,x:0}} exit={{opacity:0,x:reduced?0:-12}} transition={{duration:reduced?.1:.45}}>
   {scene<=7&&<ClassroomScene board={board} pose={pose} teacher={scene===2||scene===7?'help':scene===1?'write':'point'} focus={scene===3||scene===4?'desk':scene===1||scene===6?'leo':'room'} quiet={scene>0}>
    {scene===1&&!reaction&&<><div className="window-distraction" aria-label="A small movement outside the window"/><div className="fallen-pencil"/></>}
    {scene===2&&<div className={`worksheet-visual ${reaction?'is-split':''}`}>{reaction?<><b>STEP 1 <small>1–4</small></b><b>STEP 2 <small>5–8</small></b><b>STEP 3 <small>9–12</small></b></>:Array.from({length:12},(_,i)=><i key={i}>{i+1}</i>)}</div>}
    {scene===3&&<div className="memory-tray">{selected.length===0?<><ObjectTile type="book"/><ObjectTile type="pencil"/><ObjectTile type="bag"/></>:<span>The drawer is closed. What did you see?</span>}</div>}
    {scene===5&&answers.transition!==undefined&&answers.transition>0&&<div className="countdown-cue"><b>3 · 2 · 1</b><span>Math starts next</span></div>}
   </ClassroomScene>}
   <StoryPanel scene={scene} reaction={reaction}>
    {scene===0&&<><p className="eyebrow">Morning classroom · {learner}, age 9 · Grade 4</p><h1>Hi, {learner}. Let's see how HEBAT adapts to your learning needs.</h1><p>{learner} is a capable, curious learner. HEBAT quietly notices which everyday supports help him do his best.</p><button className="btn-primary demo-cta" onClick={()=>go()}>Start the school day <ArrowRight/></button><p className="safety-note">A short, non-diagnostic learning support story</p></>}
    {scene===1&&<Question title="A pencil drops. Something moves outside." prompt="What usually happens?" options={choices.focus} onPick={v=>answer('focus',v)} reaction={reaction}/>} 
    {scene===2&&<Question title="The worksheet has 12 questions." prompt="How does a longer task usually feel?" options={choices.task} onPick={v=>answer('task',v)} reaction={reaction} reactionText="The teacher makes the next step feel clear."/>}
    {scene===3&&<MemoryGame selected={selected} setSelected={setSelected} finish={()=>{setAnswers(x=>({...x,memory:selected.filter(x=>['book','pencil','bag'].includes(x)).length===3?0:2}));go()}}/>}
    {scene===4&&<SequenceGame sequence={sequence} setSequence={setSequence} repeats={repeats} repeat={()=>setRepeats(x=>x+1)} finish={()=>{setAnswers(x=>({...x,sequence:sequence.join(',')==='book,pencil,star'&&!repeats?0:2}));go()}}/>}
    {scene===5&&<Question title="The bell rings softly. It's time for Math." prompt="How does switching activities usually feel?" options={choices.transition} onPick={v=>answer('transition',v)} reaction={reaction} reactionText="A calm visual cue makes the next moment predictable."/>}
    {scene===6&&<Question title={`${learner} has been sitting through a long lesson.`} prompt="How does your body usually feel?" options={choices.energy} onPick={v=>answer('energy',v)} reaction={reaction}/>}
    {scene===7&&<Question title="The teacher notices the activity feels difficult." prompt="What would help most?" options={[["Show me an example",'example'],['Break it into smaller steps','steps'],['Give me more time','time'],['Remind me gently','reminder']]as const} onPick={v=>answer('support',v)} reaction={reaction} reactionText={`The teacher responds in the way ${learner} prefers.`}/>}
   </StoryPanel>
   {scene===8&&<ProfileScene name={learner} profile={profile} need={need} next={()=>go()}/>}
   {scene===9&&<section className="result-scene transform-scene"><div className="result-leo"><LeoCharacter pose="smile"/></div><div><p className="eyebrow">Support in action</p><h1>HEBAT adapts support around {learner}.</h1><p>Small changes turn the same classroom demands into clear, achievable next steps.</p><SupportTransformation/><button className="btn-primary demo-cta" onClick={()=>go()}>See {learner}'s Today Plan <ArrowRight/></button></div></section>}
   {scene===10&&<TodayScene name={learner} answers={answers} restart={restart}/>}
  </motion.div></AnimatePresence>
 </main>
}

function DemoEntry({onEnter}:{onEnter:(name:string)=>void}){
 const[name,setName]=useState('');const[password,setPassword]=useState('');
 const submit=(event:FormEvent)=>{event.preventDefault();onEnter(name)};
 return <main className="jury-demo demo-entry"><section className="demo-login-card"><div className="demo-login-brand"><span>H</span><div><b>HEBAT Jury Demo</b><small>Learning support</small></div></div><p className="eyebrow">See how HEBAT adapts to each learner</p><h1>Experience support built around the learner.</h1><p>Enter anything below to begin the classroom experience.</p><form onSubmit={submit} noValidate><label>Name<input autoFocus value={name} onChange={event=>setName(event.target.value)} placeholder="Any text" /></label><label>Password<input type="password" value={password} onChange={event=>setPassword(event.target.value)} placeholder="Any text" /></label><button className="btn-primary" type="submit">Enter Demo <ArrowRight/></button></form><small className="demo-mode-note">Demo Mode — no real account required</small><a href="/">Login to HEBAT</a></section></main>
}

function StoryPanel({children,scene,reaction}:{children:React.ReactNode;scene:number;reaction:boolean}){return <section className={`story-panel ${scene===0?'intro-panel':''}`} aria-live="polite"><div className="scene-number">{scene===0?'Arrival':`Moment ${scene} of 7`}</div>{reaction&&<div className="calm-feedback"><Check/>Got it. Let's keep going.</div>}{children}</section>}
function Question({title,prompt,options,onPick,reaction,reactionText}:{title:string;prompt:string;options:readonly(readonly[string,any])[];onPick:(v:any)=>void;reaction:boolean;reactionText?:string}){return <><p className="scene-context">{title}</p><h1>{reaction?'Leo responds calmly.':prompt}</h1>{reaction?<p>{reactionText||'Leo takes a moment, then returns to the classroom activity.'}</p>:<div className={`story-options ${options.length===4?'four':''}`}>{options.map(([label,value])=><button key={label} onClick={()=>onPick(value)}>{label}<ArrowRight/></button>)}</div>}</>}
function ObjectTile({type}:{type:'book'|'pencil'|'bag'|'apple'|'ball'}){return <div className={`object-tile object-${type}`}><span/><b>{type==='bag'?'Backpack':type[0].toUpperCase()+type.slice(1)}</b></div>}
function MemoryGame({selected,setSelected,finish}:{selected:string[];setSelected:(x:string[])=>void;finish:()=>void}){const[ready,setReady]=useState(false);if(!ready)return <><p className="scene-context">The teacher places three objects on Leo's desk.</p><h1>Please remember these.</h1><p>Take a calm look. This is one small support signal, not a clinical test.</p><button className="btn-primary demo-cta" onClick={()=>setReady(true)}>Close the drawer</button></>;return <><p className="scene-context">The drawer closes.</p><h1>What did you see?</h1><div className="memory-options">{(['book','pencil','bag','apple','ball']as const).map(x=><button className={selected.includes(x)?'chosen':''} onClick={()=>setSelected(selected.includes(x)?selected.filter(y=>y!==x):[...selected,x])} key={x}><ObjectTile type={x}/></button>)}</div><button disabled={!selected.length} className="btn-primary demo-cta" onClick={finish}>That's what I remember <ArrowRight/></button></>}
function SequenceGame({sequence,setSequence,repeats,repeat,finish}:{sequence:string[];setSequence:(x:string[])=>void;repeats:number;repeat:()=>void;finish:()=>void}){const add=(x:string)=>!sequence.includes(x)&&setSequence([...sequence,x]);return <><p className="scene-context">The instructions fade into a small visual cue.</p><h1>Help Leo complete the sequence.</h1><div className="sequence-work"><button draggable onDragStart={e=>e.dataTransfer.setData('text','book')} onClick={()=>add('book')}><ObjectTile type="book"/></button><div onDragOver={e=>e.preventDefault()} onDrop={e=>add(e.dataTransfer.getData('text'))} className={sequence.includes('book')?'placed':''}>Place book beside pencil</div><button onClick={()=>add('pencil')}><ObjectTile type="pencil"/></button><button className="star-sheet" onClick={()=>add('star')}>Tap the star <span>★</span></button></div><div className="step-order">{sequence.map((x,i)=><span key={x}>{i+1}. {x}</span>)}</div><div className="sequence-actions"><button onClick={repeat}><RefreshCcw/>Show instructions again {repeats?`(${repeats})`:''}</button><button disabled={sequence.length<3} className="btn-primary" onClick={finish}>Continue <ArrowRight/></button></div></>}
function ProfileScene({name,profile,need,next}:{name:string;profile:{label:string;score:number}[];need:(n:number)=>string;next:()=>void}){return <section className="result-scene profile-scene"><div className="profile-classroom"><LeoCharacter pose="smile"/><p>HEBAT has observed a few learning patterns.</p></div><div className="profile-content"><p className="eyebrow">Non-diagnostic learning support</p><h1>{name}'s Support Profile</h1><p>Classroom moments become practical support domains—not labels.</p><div className="profile-domains">{profile.map((x,i)=><motion.div key={x.label} initial={{opacity:0,x:15}} animate={{opacity:1,x:0}} transition={{delay:i*.1}}><span>{x.label}</span><b className={x.score>=3?'more':x.score>=1.5?'may':'well'}>{need(x.score)}</b></motion.div>)}</div><button className="btn-primary demo-cta" onClick={next}>See support adapt <ArrowRight/></button></div></section>}
function TodayScene({name,answers,restart}:{name:string;answers:Answers;restart:()=>void}){const focus=(answers.focus??0)>1;const memory=Math.max(answers.memory??0,answers.sequence??0)>1;return <section className="today-scene"><aside><LeoCharacter pose="smile"/><span>{name}</span><b>Grade 4</b></aside><div className="today-content"><p className="eyebrow">Today's plan has been adapted for {name}.</p><h1>Today</h1><p>Three clear missions. One next step at a time.</p><div className="missions"><Mission icon={<BookOpen/>} title="Reading Mission" time="6 min" tag={focus?'Shorter session':'Comfortable pace'}/><Mission icon={<Clock3/>} title="Focus Sprint" time={focus?'5 min':'8 min'} tag="One step at a time"/><Mission icon={<Eye/>} title="Memory Mission" time="4 min" tag={memory?'Visual instructions':'Gentle practice'}/></div><div className="today-actions"><button className="btn-primary">Start Reading Mission <ArrowRight/></button><button onClick={restart}>Restart Jury Demo</button></div><p className="safety-note">Demo interactions stay in this browser view and create no database records.</p></div></section>}
function Mission({icon,title,time,tag}:{icon:React.ReactNode;title:string;time:string;tag:string}){return <div><i>{icon}</i><span><b>{title}</b><small>{tag}</small></span><strong>{time}</strong></div>}
