import { useState, type FormEvent } from 'react';
import { ArrowLeft, ArrowRight, Eye, EyeOff, Globe, GraduationCap, HeartHandshake, LockKeyhole, Mail, School, Smile, Stethoscope, UserRound } from 'lucide-react';
import { useAuth } from '../lib/AuthContext';
import { useLanguage } from '../lib/LanguageContext';
import { cn } from '../lib/utils';

type Role='child'|'parent'|'teacher'|'professional';
const roles=[
  {id:'child' as Role,label:'Student',icon:GraduationCap,emoji:'🎒'},
  {id:'parent' as Role,label:'Parent',icon:HeartHandshake,emoji:'🏡'},
  {id:'teacher' as Role,label:'Teacher',icon:School,emoji:'📚'},
  {id:'professional' as Role,label:'Professional',icon:Stethoscope,emoji:'🤝'},
];
export default function AuthPage(){
  const {login,register}=useAuth(); const {language,setLanguage}=useLanguage(); const isId=language==='id';
  const [view,setView]=useState<'welcome'|'role'|'profile'|'login'>('welcome');
  const [showPassword,setShowPassword]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  const [form,setForm]=useState({role:'child' as Role,name:'',childName:'',age:'9',grade:'Grade 4',school:'',email:'',password:''});
  const choose=(role:Role)=>{setForm(f=>({...f,role}));setView('profile')};
  async function finish(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{
    const child=form.role==='child'?{age:Number(form.age),grade:form.grade,school:form.school}:{name:form.childName,age:Number(form.age),grade:form.grade,school:form.school};
    await register({...form,child});
  }catch(e:any){setError(e.message||'Unable to continue.')}finally{setBusy(false)}}
  async function signIn(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await login(form.email,form.password)}catch(e:any){setError(e.message||'Unable to sign in.')}finally{setBusy(false)}}
  return <main className="min-h-screen bg-background flex items-center justify-center p-4 md:p-8"><section className="w-full max-w-2xl bg-white rounded-[32px] border-2 border-surface-variant shadow-ambient-lg p-5 sm:p-9">
    <header className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="w-12 h-12 rounded-2xl bg-primary text-white border-b-4 border-primary-dark flex items-center justify-center"><Smile/></div><div><div className="text-2xl font-black text-primary">HEBAT</div><div className="text-[10px] font-black uppercase tracking-widest text-neutral-400">Learning support</div></div></div><button onClick={()=>setLanguage(isId?'en':'id')} className="btn-outline !py-2 !px-3 text-xs"><Globe className="w-4 h-4"/>{language.toUpperCase()}</button></header>
    {view==='welcome'&&<div className="text-center py-10"><div className="text-6xl">🌟</div><h1 className="text-3xl sm:text-4xl font-black mt-5">{isId?'Mulai dengan HEBAT':'A simpler way to start'}</h1><p className="text-base font-bold text-neutral-500 mt-3">{isId?'Buat ruang dukungan dalam dua langkah singkat.':'Create your support space in two short steps.'}</p><div className="space-y-3 mt-8"><a href="/demo" className="btn-primary w-full !py-4">Try Jury Demo <ArrowRight className="w-5 h-5"/></a><button onClick={()=>setView('role')} className="btn-outline w-full !py-4">Create account</button><button onClick={()=>setView('login')} className="text-sm font-black text-primary mt-3 cursor-pointer">Login to HEBAT</button></div></div>}
    {view==='role'&&<div className="py-7"><StepBack onClick={()=>setView('welcome')}/><div className="text-xs font-black uppercase tracking-widest text-primary mt-6">Step 1 of 2</div><h1 className="text-3xl font-black mt-2">Who are you using HEBAT as?</h1><div className="grid grid-cols-2 gap-3 mt-7">{roles.map(r=><button key={r.id} onClick={()=>choose(r.id)} className="rounded-3xl border-2 border-b-4 border-surface-variant hover:border-primary bg-white p-5 min-h-36 text-left cursor-pointer focus:outline-none focus:ring-4 focus:ring-primary/20"><span className="text-4xl">{r.emoji}</span><span className="block text-lg font-black mt-3">{r.label}</span><r.icon className="w-4 h-4 text-neutral-400 mt-2"/></button>)}</div></div>}
    {view==='profile'&&<form onSubmit={finish} className="py-7"><StepBack onClick={()=>setView('role')}/><div className="text-xs font-black uppercase tracking-widest text-primary mt-6">Step 2 of 2</div><h1 className="text-3xl font-black mt-2">Tell us just the basics</h1><div className="space-y-4 mt-7"><label className="auth-label">First name<input className="auth-input mt-2" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required placeholder="Your first name"/></label>{form.role!=='child'&&form.role!=='professional'&&<label className="auth-label">{form.role==='teacher'?'Student first name':'Child first name'}<input className="auth-input mt-2" value={form.childName} onChange={e=>setForm({...form,childName:e.target.value})} required/></label>}{form.role==='teacher'&&<label className="auth-label">School / Class name<input className="auth-input mt-2" value={form.school} onChange={e=>setForm({...form,school:e.target.value})}/></label>}{form.role!=='professional'&&<div className="grid grid-cols-2 gap-3"><label className="auth-label">{form.role==='child'?'Age':'Child age'}<input type="number" min="4" max="17" className="auth-input mt-2" value={form.age} onChange={e=>setForm({...form,age:e.target.value})} required/></label><label className="auth-label">Grade<input className="auth-input mt-2" value={form.grade} onChange={e=>setForm({...form,grade:e.target.value})} required/></label></div>}{<><label className="auth-label">Email<input type="email" className="auth-input mt-2" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></label><label className="auth-label">Password<input type="password" minLength={8} className="auth-input mt-2" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required placeholder="8+ characters with a number"/></label></>} {error&&<ErrorBox text={error}/>}<button disabled={busy} className="btn-primary w-full !py-4">{busy?'Creating your space…':'Create my account'}<ArrowRight className="w-5 h-5"/></button></div></form>}
    {view==='login'&&<form onSubmit={signIn} className="py-7"><StepBack onClick={()=>setView('welcome')}/><h1 className="text-3xl font-black mt-7">Welcome back</h1><div className="space-y-4 mt-7"><label className="auth-label flex items-center gap-2"><Mail className="w-4 h-4"/>Email</label><input type="email" className="auth-input" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/><label className="auth-label flex items-center gap-2"><LockKeyhole className="w-4 h-4"/>Password</label><div className="relative"><input type={showPassword?'text':'password'} className="auth-input !pr-12" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/><button type="button" onClick={()=>setShowPassword(!showPassword)} className="absolute right-4 top-1/2 -translate-y-1/2">{showPassword?<EyeOff/>:<Eye/>}</button></div>{error&&<ErrorBox text={error}/>}<button disabled={busy} className="btn-primary w-full !py-4">Sign in</button></div></form>}
  </section></main>
}
function StepBack({onClick}:{onClick:()=>void}){return <button onClick={onClick} type="button" className="text-sm font-black text-neutral-500 flex gap-2 items-center cursor-pointer"><ArrowLeft className="w-4 h-4"/>Back</button>}
function ErrorBox({text}:{text:string}){return <div className="rounded-2xl bg-error-container text-on-error-container border-2 border-error/20 p-4 text-sm font-extrabold">{text}</div>}
