import { useState } from 'react';
import { Link2, LogOut, Plus, Smile, UserRoundPlus } from 'lucide-react';
import { useAuth } from '../lib/AuthContext';
import { useLanguage } from '../lib/LanguageContext';

export default function NoLinkedChild(){
  const {user,createChild,linkChild,logout} = useAuth();
  const {language} = useLanguage(); const isId=language==='id';
  const [mode,setMode]=useState<'create'|'link'>(user?.role==='professional'?'link':'create'); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  const [form,setForm]=useState({name:'',age:'9',grade:'Grade 4',school:''}); const [code,setCode]=useState('');
  async function submit(){setBusy(true);setError('');try{if(mode==='create') await createChild({...form,age:Number(form.age)}); else await linkChild(code);}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  return <div className="min-h-screen bg-background flex items-center justify-center p-5"><div className="w-full max-w-xl card-pillowy !p-8 md:!p-10">
    <div className="flex justify-between gap-4"><div className="w-12 h-12 rounded-2xl bg-primary text-white border-b-4 border-primary-dark flex items-center justify-center"><Smile/></div><button onClick={logout} className="btn-outline !py-2 !px-3 text-xs"><LogOut className="w-4 h-4"/>{isId?'Keluar':'Sign out'}</button></div>
    <h1 className="text-3xl font-black mt-6">{isId?'Hubungkan profil anak':'Connect a child profile'}</h1><p className="text-neutral-500 font-bold mt-2">{user?.role==='parent'?(isId?'Buat profil anak atau hubungkan kode dari akun anak.':'Create a child profile or link an existing child code.'):user?.role==='teacher'?(isId?'Tambahkan siswa pertama atau gunakan kode yang dibagikan keluarga.':'Add the first student or use a code shared by the family.'):(isId?'Tambahkan kasus demo atau hubungkan kode rujukan yang tersedia.':'Add a demo case or connect an available child code.')}</p>
    {user?.role!=='professional'?<div className="grid grid-cols-2 gap-2 bg-neutral-100 p-1.5 rounded-2xl mt-6"><button onClick={()=>setMode('create')} className={`py-3 rounded-xl text-sm font-black ${mode==='create'?'bg-white border-2 border-surface-variant':''}`}><UserRoundPlus className="w-4 h-4 inline mr-2"/>{isId?'Buat':'Create'}</button><button onClick={()=>setMode('link')} className={`py-3 rounded-xl text-sm font-black ${mode==='link'?'bg-white border-2 border-surface-variant':''}`}><Link2 className="w-4 h-4 inline mr-2"/>{isId?'Kode':'Link code'}</button></div>:<div className="rounded-2xl bg-secondary-container/20 border border-secondary/20 p-4 mt-6"><div className="text-xs font-black text-secondary-dark">{isId?'Akses profesional berbasis persetujuan':'Consent-based professional access'}</div><p className="text-xs font-bold text-neutral-500 mt-1">{isId?'Masukkan kode profil dari rujukan yang sudah disetujui orang tua.':'Enter the child profile code from a referral with guardian consent.'}</p></div>}
    {mode==='create'?<div className="space-y-3 mt-6"><input className="auth-input" placeholder={isId?'Nama anak/siswa':'Child / student name'} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><div className="grid grid-cols-2 gap-3"><input className="auth-input" type="number" min="4" max="17" value={form.age} onChange={e=>setForm({...form,age:e.target.value})}/><input className="auth-input" value={form.grade} onChange={e=>setForm({...form,grade:e.target.value})}/></div><input className="auth-input" placeholder={isId?'Sekolah':'School'} value={form.school} onChange={e=>setForm({...form,school:e.target.value})}/></div>:<div className="mt-6"><label className="auth-label">{isId?'Kode profil anak':'Child profile code'}</label><input className="auth-input mt-2 uppercase tracking-widest" placeholder="LEO2026A" value={code} onChange={e=>setCode(e.target.value)}/><p className="text-xs font-bold text-neutral-400 mt-2">Demo: LEO2026A</p></div>}
    {error&&<div className="mt-4 bg-error-container text-on-error-container p-3 rounded-xl font-bold text-sm">{error}</div>}
    <button disabled={busy || (mode==='create'?!form.name.trim():!code.trim())} onClick={submit} className="btn-primary w-full mt-6 disabled:opacity-50"><Plus className="w-4 h-4"/>{busy?(isId?'Menyimpan...':'Saving...'):mode==='create'?(isId?'Buat Profil':'Create Profile'):(isId?'Hubungkan':'Connect')}</button>
  </div></div>
}
