import {useMemo,useRef,useState} from 'react'; import {ArrowRight,CheckCircle2,Info,Sparkles,Star} from 'lucide-react'; import type{Page}from'../types'; import {useAuth}from'../lib/AuthContext'; import {useHebatData}from'../lib/HebatDataContext'; import {buildSupportProfile,recommendations,type ScreeningResponse}from'../lib/screening/engine'; import {MemoryChallenge,ScenarioChoice,ScreeningProgress,ScreeningShell,SequenceChallenge,SupportProfileCard}from'../components/screening/ScreeningComponents';
interface Props{step:Page;setPage:(p:Page)=>void}
type Q={id:string;title:string;hint?:string;domain?:any;options?:Array<{id:string;label:string;emoji?:string;score:number}>;kind?:'memory'|'sequence'|'multi'};
const student:Q[]=[
{id:'focus',title:'Homework is open. A notification pops up. What usually happens?',domain:'attention',options:[['keep','I keep working','🎯',0],['return','I get distracted, but come back','↩️',1],['stop','I usually stop','🛑',3]].map(a=>({id:String(a[0]),label:String(a[1]),emoji:String(a[2]),score:Number(a[3])}))},
{id:'length',title:'When a task takes 20 minutes, what usually happens?',domain:'task_persistence',options:[['finish','I finish it','✅',0],['reminders','I need reminders','🔔',2],['leave','I often leave it unfinished','⏸️',3]].map(a=>({id:String(a[0]),label:String(a[1]),emoji:String(a[2]),score:Number(a[3])}))},
{id:'memory',title:'Remember these three things',hint:'Look carefully, then tap “I’m ready”.',kind:'memory',domain:'working_memory'},
{id:'sequence',title:'Follow the steps in order',hint:'Blue book → pencil → star',kind:'sequence',domain:'working_memory'},
{id:'routine',title:'How often do you need reminders for your morning routine?',domain:'routine',options:[['never','Never','🌞',0],['sometimes','Sometimes','🔔',1],['often','Often','🔁',3]].map(a=>({id:String(a[0]),label:String(a[1]),emoji:String(a[2]),score:Number(a[3])}))},
{id:'transition',title:'A game ends and homework starts. What feels closest?',domain:'transition',options:[['easy','Easy to switch','👍',0],['time','I need a little time','⏳',1],['hard','Very hard to stop','🎮',3]].map(a=>({id:String(a[0]),label:String(a[1]),emoji:String(a[2]),score:Number(a[3])}))},
{id:'find',title:'Quick find: tap the school bag',domain:'attention',options:[['book','Book','📘',1],['bag','School bag','🎒',0],['ball','Ball','⚽',1],['apple','Apple','🍎',1]].map(a=>({id:String(a[0]),label:String(a[1]),emoji:String(a[2]),score:Number(a[3])}))},
{id:'energy',title:'How does your body feel when you sit and work?',domain:'self_regulation',options:[['calm','Calm','🙂',0],['restless','Restless','🌀',3],['tired','Tired','😴',2],['energetic','Very energetic','⚡',2]].map(a=>({id:String(a[0]),label:String(a[1]),emoji:String(a[2]),score:Number(a[3])}))},
{id:'preference',title:'What helps most when something feels difficult?',options:[['example','Show me an example','👀',0],['smaller','Break it into smaller steps','🧩',0],['time','Give me more time','⏱️',0],['gentle','Remind me gently','💬',0]].map(a=>({id:String(a[0]),label:String(a[1]),emoji:String(a[2]),score:Number(a[3])}))},
{id:'school',title:'Which school situations feel most difficult?',hint:'Choose one or two.',kind:'multi',options:[['listen','Listening for a long time','👂',3],['finish','Finishing assignments','📝',3],['remember','Remembering instructions','🧠',3],['change','Changing activities','↔️',3],['organise','Organising things','🗂️',3]].map(a=>({id:String(a[0]),label:String(a[1]),emoji:String(a[2]),score:Number(a[3])}))},];
const observer=(teacher:boolean):Q[]=>[
{id:'attention',title:teacher?'During independent work, what usually happens?':'During homework, what usually happens?',domain:'attention'},
{id:'steps',title:'A task with 3 steps is given. What usually happens?',domain:'working_memory'},
{id:'finish',title:'How often is support needed to finish a task?',domain:'task_persistence'},
{id:'routine',title:teacher?'How often are classroom routine prompts needed?':'How often are home routine reminders needed?',domain:'routine'},
{id:'transition',title:'How do transitions between activities usually go?',domain:'transition'},
{id:'energy',title:'How often does restlessness make work harder?',domain:'self_regulation'},
].map(q=>({...q,options:[{id:'well',label:'Usually manages independently',emoji:'🌱',score:0},{id:'some',label:'Needs some support',emoji:'🤝',score:2},{id:'more',label:'Needs repeated support',emoji:'🧩',score:3}]}));
export default function Screening({step,setPage}:Props){const{user,refreshMe}=useAuth();const{saveScreening,data}=useHebatData();const role=user?.role||'child';const qs=useMemo(()=>role==='child'?student:observer(role==='teacher'),[role]);const[index,setIndex]=useState(0);const[value,setValue]=useState<string|string[]>('');const[responses,setResponses]=useState<ScreeningResponse[]>([]);const[showMemory,setShowMemory]=useState(true);const[repeats,setRepeats]=useState(0);const[saving,setSaving]=useState(false);const[result,setResult]=useState<any>(null);const started=useRef(new Date().toISOString());const dashboard:Page=role==='teacher'?'teacher-dashboard':role==='parent'?'parent-dashboard':'child-dashboard';
 if(step==='screening-intro')return <ScreeningShell><div className="card-pillowy !p-8 sm:!p-10 text-center mt-8"><div className="text-6xl">🦁</div><div className="text-xs font-black uppercase tracking-widest text-primary mt-5">{role==='teacher'?'Teacher Observation':'HEBAT Check-in'}</div><h1 className="text-3xl sm:text-4xl font-black mt-2">{role==='child'?"Let's understand how you learn best.":role==='teacher'?'A quick classroom observation':"Let's understand what support helps."}</h1><p className="text-base font-bold text-neutral-500 mt-4">This short activity helps HEBAT personalise support. It is not a medical diagnosis.</p><button onClick={()=>setPage('screening-quiz')} className="btn-primary w-full mt-8 !py-4">Start My Check-in <ArrowRight/></button><button onClick={()=>{sessionStorage.setItem(`hebat_screening_later_${user?.id}`,'1');setPage(dashboard)}} className="text-sm font-black text-neutral-500 mt-5 cursor-pointer">Do this later</button></div></ScreeningShell>;
 if(step==='screening-results'&&result){const recs=recommendations(result,responses.find(r=>r.id==='preference')?.value as string);const high=result.domains.some((d:any)=>d.need==='High');return <ScreeningShell><div className="card-pillowy !p-7 sm:!p-9 mt-5"><div className="text-center"><div className="w-16 h-16 bg-primary-container rounded-3xl mx-auto flex items-center justify-center"><CheckCircle2 className="w-9 h-9 text-primary"/></div><div className="text-xs font-black uppercase tracking-widest text-primary mt-5">HEBAT Support Profile</div><h1 className="text-3xl font-black mt-2">Your Support Profile</h1><div className="inline-flex items-center gap-2 bg-amber-50 text-amber-800 rounded-full px-4 py-2 font-black text-sm mt-3"><Star className="w-4 h-4 fill-current"/>Profile complete! +20 Stars</div></div><div className="space-y-3 mt-7">{result.domains.map((d:any)=><SupportProfileCard key={d.key} {...d}/>)}</div><h2 className="text-xl font-black mt-7">What HEBAT will do</h2><div className="space-y-2 mt-3">{recs.map((x:string)=><div key={x} className="rounded-2xl bg-primary-container/20 border border-primary/20 px-4 py-3 font-bold flex gap-3"><Sparkles className="w-5 h-5 text-primary shrink-0"/>{x}</div>)}</div>{high&&<p className="mt-5 text-sm font-black text-amber-800">Further review may be helpful. Talk to a Parent, Teacher, or Professional.</p>}<div className="mt-6 rounded-2xl bg-neutral-50 border border-surface-variant p-4 flex gap-3"><Info className="w-5 h-5 shrink-0"/><p className="text-sm font-bold text-neutral-600">HEBAT's Support Profile is designed to personalise learning and everyday support. It is not a medical diagnosis.</p></div><button onClick={()=>setPage('support-plan')} className="btn-primary w-full mt-6 !py-4">Build My Plan <ArrowRight/></button>{(data?.screenings?.length||0)>1&&<p className="text-center text-xs font-bold text-neutral-500 mt-4">This check-in was added to history. Previous results were not overwritten.</p>}</div></ScreeningShell>}
 const q=qs[index];const valid=Array.isArray(value)?value.length>0:Boolean(value);async function next(){let signal=0;if(q.kind==='memory'){const correct=(value as string[]).filter(x=>['book','pencil','bag'].includes(x)).length;signal=correct===3?0:correct===2?1:3}else if(q.kind==='sequence')signal=(value as string[]).join(',')==='book,pencil,star'&&repeats===0?0:repeats?2:3;else signal=q.options?.find(o=>o.id===value)?.score||0;const signals:any={};if(q.domain)signals[q.domain]=signal;if(q.id==='school'){for(const x of value as string[]){signals[x==='listen'?'attention':x==='finish'?'task_persistence':x==='remember'||x==='organise'?'working_memory':'transition']=3}}const nextResponses=[...responses,{id:q.id,value,signals}];setResponses(nextResponses);if(index<qs.length-1){setIndex(index+1);setValue(qs[index+1].kind==='memory'||qs[index+1].kind==='sequence'||qs[index+1].kind==='multi'?[]:'');setShowMemory(true);return}const profile=buildSupportProfile(nextResponses);setSaving(true);await saveScreening({startedAt:started.current,responses:nextResponses,supportProfile:profile,nonDiagnostic:true,instrument:role==='child'?'student-playful-check-in':role==='teacher'?'teacher-observation':'parent-observation'});await refreshMe();setResult(profile);setSaving(false);setPage('screening-results')}
 return <ScreeningShell onBack={()=>index?setIndex(index-1):setPage('screening-intro')}><ScreeningProgress current={index+1} total={qs.length}/><div className="py-9 text-center"><div className="text-xs font-black uppercase tracking-widest text-primary">{role==='teacher'?'Teacher Observation':'Quick challenge'}</div><h1 className="text-2xl sm:text-3xl font-black mt-3">{q.title}</h1>{q.hint&&<p className="text-sm font-bold text-neutral-500 mt-2">{q.hint}</p>}{q.kind==='memory'?<MemoryChallenge revealed={showMemory} onReady={()=>{setShowMemory(false);setValue([])}} value={value as string[]} onChange={setValue}/>:q.kind==='sequence'?<SequenceChallenge value={value as string[]} onChange={setValue} onRepeat={()=>setRepeats(x=>x+1)}/>:<ScenarioChoice options={q.options!.map(({id,label,emoji})=>({id,label,emoji}))} value={value} onChange={setValue} multiple={q.kind==='multi'}/>} {index===2&&role==='child'&&<div className="text-sm font-black text-tertiary-dark mt-5">Great progress! 🌟</div>}<button disabled={!valid||saving||(q.kind==='memory'&&showMemory)} onClick={next} className="btn-primary w-full mt-8 !py-4 disabled:opacity-40">{saving?'Building your Support Profile…':index===qs.length-1?'Finish Check-in':'Next'}<ArrowRight/></button></div></ScreeningShell>}
