import React from 'react';
import { motion } from 'motion/react';
import { BookOpen, ClipboardCheck, Globe, HeartHandshake, History, Home, LogOut, MessageCircle, ShieldCheck, Smile, Stethoscope, Timer, Trophy, UserRound, Users } from 'lucide-react';
import { cn } from '../lib/utils';
import type { Page } from '../types';
import { useLanguage } from '../lib/LanguageContext';
import { useHebatData } from '../lib/HebatDataContext';
import { useAuth } from '../lib/AuthContext';

interface LayoutProps { children:React.ReactNode; currentPage:Page; setPage:(page:Page)=>void; role:'parent'|'child'|'teacher'|'professional'; }

export default function Layout({ children, currentPage, setPage, role }: LayoutProps) {
  const { language,setLanguage }=useLanguage();
  const { data,selectedChildId,setSelectedChildId }=useHebatData();
  const { user,linkedChildren,logout }=useAuth();
  const dashboard:Page=role==='parent'?'parent-dashboard':role==='teacher'?'teacher-dashboard':role==='professional'?'professional-dashboard':'child-dashboard';
  const nav=role==='child'?[{id:'child-dashboard' as Page,label:language==='id'?'Hari Ini':'Today',icon:Home},{id:'focus-timer' as Page,label:language==='id'?'Fokus':'Focus',icon:Timer},{id:'routine-builder' as Page,label:language==='id'?'Rutinitas':'Routine',icon:ClipboardCheck},{id:'rewards' as Page,label:language==='id'?'Bintang':'Rewards',icon:Trophy}]:role==='parent'?[{id:'parent-dashboard' as Page,label:language==='id'?'Hari Ini':'Today',icon:Home},{id:'support-plan' as Page,label:language==='id'?'Rencana':'Support Plan',icon:ShieldCheck},{id:'pmt-modules' as Page,label:'Parent Coach',icon:HeartHandshake},{id:'consultation' as Page,label:language==='id'?'Rujukan':'Referral',icon:MessageCircle}]:role==='teacher'?[{id:'teacher-dashboard' as Page,label:language==='id'?'Kelas':'Classroom',icon:Users},{id:'support-plan' as Page,label:language==='id'?'Rencana':'Support Plan',icon:ShieldCheck},{id:'screening-intro' as Page,label:'ACTRS',icon:ClipboardCheck},{id:'consultation' as Page,label:language==='id'?'Kolaborasi':'Collaboration',icon:MessageCircle}]:[{id:'professional-dashboard' as Page,label:language==='id'?'Rujukan':'Referrals',icon:Stethoscope},{id:'support-plan' as Page,label:language==='id'?'Rencana':'Support Plan',icon:ShieldCheck},{id:'consultation' as Page,label:language==='id'?'Kolaborasi':'Collaboration',icon:MessageCircle}];
  const roleName={child:language==='id'?'Siswa':'Student',parent:language==='id'?'Orang Tua':'Parent',teacher:language==='id'?'Guru':'Teacher',professional:language==='id'?'Profesional':'Professional'}[role];

  return <div className="min-h-screen flex flex-col md:flex-row bg-[#f8fafc] text-on-surface">
    <aside className="hidden md:flex flex-col w-72 bg-white fixed h-full z-40 border-r-2 border-surface-variant">
      <div className="p-5 border-b border-surface-variant/50 flex items-center justify-between"><button onClick={()=>setPage(dashboard)} className="flex items-center gap-3 text-left cursor-pointer"><div className="w-10 h-10 rounded-2xl bg-primary flex items-center justify-center text-white border-b-4 border-primary-dark"><Smile className="w-6 h-6"/></div><div><div className="text-2xl font-black text-primary tracking-tight">HEBAT</div><div className="text-[10px] font-black text-neutral-400 uppercase tracking-widest">Support Loop 2.0</div></div></button><button onClick={()=>setLanguage(language==='en'?'id':'en')} className="px-2.5 py-1.5 bg-neutral-100 border border-neutral-300 rounded-xl text-xs font-black uppercase flex items-center gap-1.5 cursor-pointer"><Globe className="w-3.5 h-3.5"/>{language.toUpperCase()}</button></div>

      <div className="px-5 pt-4 space-y-2">
        <button onClick={()=>setPage('account-history')} className="w-full bg-neutral-50 border border-surface-variant rounded-2xl p-3 flex items-center gap-3 text-left cursor-pointer hover:border-primary/40"><div className="w-9 h-9 rounded-xl bg-primary-container text-primary flex items-center justify-center"><UserRound className="w-4 h-4"/></div><div className="min-w-0 flex-1"><div className="text-[10px] uppercase font-black tracking-wider text-neutral-400">{roleName}</div><div className="text-xs font-black truncate">{user?.name}</div><div className="text-[10px] font-bold text-neutral-400 truncate">{user?.email}</div></div><History className="w-4 h-4 text-neutral-300"/></button>
        {linkedChildren.length>1?<select value={selectedChildId||''} onChange={e=>setSelectedChildId(e.target.value)} className="w-full bg-white border-2 border-surface-variant rounded-xl px-3 py-2.5 text-xs font-black outline-none focus:border-primary">{linkedChildren.map(c=><option key={c.id} value={c.id}>{c.name} · {c.grade}</option>)}</select>:<div className="bg-white border-2 border-surface-variant rounded-xl px-3 py-2.5"><div className="text-[9px] uppercase tracking-widest font-black text-neutral-400">{language==='id'?'Profil aktif':'Active profile'}</div><div className="text-xs font-black mt-0.5">{data?.child?.name || linkedChildren[0]?.name}</div></div>}
      </div>

      <nav className="flex-1 px-4 py-5 space-y-2">{nav.map(item=>{const active=currentPage===item.id||(item.id==='screening-intro'&&currentPage.startsWith('screening-'));return <motion.button key={item.id} whileTap={{scale:.98}} onClick={()=>setPage(item.id)} className={cn('w-full flex items-center gap-3.5 px-4 py-3 rounded-2xl border-2 text-xs font-black uppercase tracking-wider transition-all cursor-pointer',active?'bg-primary-container/50 border-primary border-b-4 text-primary-dark':'border-transparent text-neutral-600 hover:bg-neutral-100')}><item.icon className="w-4 h-4 shrink-0"/><span>{item.label}</span></motion.button>})}{role==='child'&&<button onClick={()=>setPage('learn-modules')} className="w-full flex items-center gap-3.5 px-4 py-3 rounded-2xl border-2 border-transparent text-xs font-black uppercase tracking-wider text-neutral-500 hover:bg-neutral-100 cursor-pointer"><BookOpen className="w-4 h-4"/>{language==='id'?'Pustaka Aktivitas':'Activity Library'}</button>}</nav>
      <div className="p-4 border-t border-surface-variant/50 space-y-2"><div className="bg-neutral-50 border border-surface-variant rounded-2xl p-3"><div className="text-[10px] font-black uppercase text-neutral-400 tracking-wider">{language==='id'?'Non-diagnostik':'Non-diagnostic'}</div><p className="text-xs font-bold text-neutral-600 leading-relaxed mt-1">{language==='id'?'HEBAT membantu dukungan belajar dan koordinasi. Diagnosis tetap dilakukan profesional.':'HEBAT supports learning and coordination. Clinical diagnosis remains with qualified professionals.'}</p></div><button onClick={logout} className="btn-outline w-full !py-2.5 text-xs"><LogOut className="w-4 h-4"/>{language==='id'?'Keluar akun':'Sign out'}</button></div>
    </aside>

    <main className="flex-1 min-w-0 md:ml-72 pb-24 md:pb-0"><div className="md:hidden sticky top-0 z-40 bg-white border-b-2 border-surface-variant px-4 py-3 flex items-center justify-between gap-3"><button onClick={()=>setPage(dashboard)} className="flex items-center gap-2"><div className="w-9 h-9 rounded-xl bg-primary text-white border-b-4 border-primary-dark flex items-center justify-center"><Smile className="w-5 h-5"/></div><div className="font-black text-primary text-lg">HEBAT</div></button><button onClick={()=>setPage('account-history')} className="flex items-center gap-2 rounded-xl bg-neutral-100 px-3 py-2 min-w-0"><div className="min-w-0 text-right"><div className="text-[9px] font-black uppercase text-neutral-400">{data?.child?.name}</div><div className="text-[11px] font-black truncate max-w-28">{user?.name}</div></div><UserRound className="w-4 h-4"/></button></div><div className="hidden md:block fixed top-0 right-0 left-72 h-1 bg-neutral-100 z-50"><motion.div key={currentPage} initial={{width:0}} animate={{width:'100%'}} transition={{duration:.5}} className="h-full bg-primary"/></div>{children}</main>

    <nav className="md:hidden fixed bottom-0 left-0 right-0 bg-white border-t-2 border-surface-variant z-50 px-2 py-2 grid gap-1" style={{gridTemplateColumns:`repeat(${nav.length}, minmax(0, 1fr))`}}>{nav.map(item=>{const active=currentPage===item.id||(item.id==='screening-intro'&&currentPage.startsWith('screening-'));return <button key={item.id} onClick={()=>setPage(item.id)} className={cn('min-h-14 rounded-2xl flex flex-col items-center justify-center gap-1 text-[10px] font-black uppercase cursor-pointer',active?'bg-primary-container text-primary-dark':'text-neutral-500')}><item.icon className="w-5 h-5"/><span className="truncate max-w-full">{item.label}</span></button>})}</nav>
  </div>
}
